version: "3.4"
services:
  db_test:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pswd
      - MYSQL_PASSWORD=pswd
      - MYSQL_USER=johndoe
      - MYSQL_DATABASE=johndoe
  app_test:
    build:
      context: .
      dockerfile: ./testDockerfile
    ports:
      - 8000:8000
    env_file:
      - ./tests/env/app.env
    depends_on:
      - db_test
    volumes:
      - ./tests/report:/src/go/tests/report
  # etcd:
  #   image: docker.io/bitnami/etcd:3
  #   environment:
  #     - ALLOW_NONE_AUTHENTICATION=yes
  #   ports:
  #     - 2379:2379
  #     - 2380:2380



