version: "3.4"
services:
  db_test:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pswd
      - MYSQL_PASSWORD=pswd
      - MYSQL_USER=johndoe
      - MYSQL_DATABASE=johndoe
      - MYSQL_TCP_PORT=3306
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
  app_test:
    build:
      context: .
      dockerfile: ./testDockerfile
    ports:
      - 8080:8000
    depends_on:
      - db_test
    volumes:
      - ./report:/src/go/tests/report
      - ./cmd/app/config/config.test.yaml:/configs/config.test.yaml
      - ./migrations:/migrations





