version: "3.4"
services:
  db_test:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql_test:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pswd
      - MYSQL_PASSWORD=pswd
      - MYSQL_USER=johndoe
      - MYSQL_DATABASE=johndoe
      - MYSQL_TCP_PORT=3306

  app_test:
    build:
      context: .
      dockerfile: ./testDockerfile
    command: ["./server","--config","/configs/config.test.yaml"]
    ports:
      - 8080:8000
    depends_on:
      - db_test
    volumes:
      - ./cmd/app/config/config.test.yaml:/configs/config.test.yaml





